Models/Reserva.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kalea2.Models
{
    public class Reserva
    {
        public int Id { get; set; }


        [DataType(DataType.Date)]
        [Display(Name = "Fecha Entrega")]
        [DisplayFormat(DataFormatString = "{0:YYYY-MM-DD}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage ="Debe seleccionar una fecha de entrega")]
        public DateTime FechaEntrega { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha Entrega")]
        [DisplayFormat(DataFormatString = "{0:YYYY-MM-DD}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Debe seleccionar una fecha de entrega")]
        public string FechaEntrega2 { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Horario Inicio")]
        public string FechaInicio { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Horario Fin")]
        public string FechaFin { get; set; }
        [Range(0, double.MaxValue, ErrorMessage = "Ingrese un numero valido")]
        public double TiempoArmado { get; set; }
        [DataType(DataType.Time)]
        [Display(Name = "Horario R. Inicio")]
        public string FechaRestriccionInicio { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Horario R. Fin")]
        public string FechaRestriccionFin { get; set; }

        [Required(ErrorMessage = "Ingrese una direccion de entrega")]
        public string DireccionEntrega { get; set; }
        public string DireccionFiscal { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        //[Required(ErrorMessage = "Ingrese una zona de entrega")]
        public string Zona { get; set; }
        public string Coordenadas { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Ingrese un nombre de cliente")]
        public string NombreCliente { get; set; }
        public string NitCliente { get; set; }
        
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Ingrese un numero de telefono")]
        public string Telefono { get; set; }

        [DataType(DataType.PhoneNumber)]        
        [Required(ErrorMessage = "Ingrese un numero de celular")]
        public string Celular { get; set; }

        [DataType(DataType.Text)]
        //[Required(ErrorMessage = "Ingrese un nombre de la persona que recibe")]
        public string PersonaRecepcion { get; set; }
        
        [DataType(DataType.MultilineText)]
        public string ComentariosVenta { get; set; }
        
        [DataType(DataType.MultilineText)]
        public string ComentariosTorre { get; set; }
        
        public string Estado { get; set; }
        
        public string UsrCreacion { get; set; }
        
        public string FechaCreacion { get; set; }
        
        public string NumeroEntregaDia { get; set; }
        
        public string Vehiculo { get; set; }
        public string NumVehiculo { get; set; }
        public string NumEvento { get; set; }

        public string ListadoEventosCasos { get; set; }

        public string ColorTipoEvento { get; set; }

        [Required(ErrorMessage = "Ingrese una zona de entrega")]
        public string ZonaDireccion { get; set; }

        public int TiempoRuta { get; set; }
        public string ReferenciaReserva { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Debe ingresar una Geolocalización para la entrega")]
        public string Geolocalizacion { get; set; }
        public string FechaArmado { get; set; }
        //[Required(ErrorMessage = "Seleccione un tipo de instalación")]
        public string TipoDeInstalacion { get; set; }
        public int TamanioTarjeta { get; set; }

        public int TiempoRestante { get; set; }
        public DateTime FechaArmadoT { get; set; }

        public DateTime FechaRestriccionI { get; set; }
        public DateTime FechaRestriccionF { get; set; }
        public DateTime FechaInicioOrdenar { get; set; }
        public List<Models.Reserva_Detalle_Casos> Reserva_Casos { get; set; }
        public List<Models.Reserva_Detalle_Articulos> Reserva_Articulos { get; set; }
        public List<SelectListItem> Eventos_Articulos;
        public List<SelectListItem> Casos_Pendientes;
        public List<SelectListItem> TiposDeInstalacion { get; set; }
        public int TamanioTarjetaTranspareante { get; set; }
        public string NombreFactura { get; set; }
    }
}

Models/Traslados.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace kalea2.Models
{
    public class Traslados
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha Entrega")]
        [DisplayFormat(DataFormatString = "{0:YYYY-MM-DD}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Debe seleccionar una fecha de traslado")]
        public DateTime FechaEntrega { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha Entrega")]
        [DisplayFormat(DataFormatString = "{0:YYYY-MM-DD}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Debe seleccionar una fecha de traslado")]
        public string FechaEntrega2 { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Horario Inicio")]
        [Required(ErrorMessage = "Debe seleccionar una hora de incio")]
        public string FechaRestriccionInicio { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Horario Fin")]
        [Required(ErrorMessage = "Debe seleccionar una hora de finalización")]
        public string FechaRestriccionFin { get; set; }

        public string Tipo { get; set; }

        public string Vehiculo { get; set; }
    }
}

Controllers/ReservasController.cs
using kalea2.Utilidades;

using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kalea2.Controllers
{
    public class ReservasController : Controller
    {
        // GET: Reservas
        [AuthorizeUser(idOperacion: 0, pantalla: 7)]
        public ActionResult Index()
        {
            if (TempData["0"] !=null)
            {
                var t = TempData["0"].ToString();
                if (!string.IsNullOrEmpty(t))
                {
                    if (t.Contains("Error"))
                    {
                        ViewBag.Mensaje = t;
                    }
                    else if (t.Contains("Entrega"))
                    {
                        ViewBag.Exitoso = t;
                    }
                }
            }

            char[] delimitadores = { '=', '+' };
            if (TempData["7"] != null)
            {
                Reservas reservas = new Reservas();
                DateTime dt = Convert.ToDateTime(TempData["7"].ToString());
                var listado = reservas.ListadoReservas(dt);
                TempData["5"] = dt.ToString("dd/MM/yyyy");
                return View("Index", listado);
            }
            else
            {
                string[] split = this.Request.RawUrl.Split(delimitadores);
                if (split.Length > 1)
                {
                    Reservas reservas = new Reservas();
                    reservas.AnularEventosReservas();
                    if (string.IsNullOrEmpty(split[1]))
                    {
                        var listado2 = reservas.ListadoReservas(DateTime.Today);
                        TempData["5"] = DateTime.Today.ToString("dd/MM/yyyy");
                        return View("Index", listado2);
                    }
                    DateTime.TryParse(split[1] + " " + split[2] + " " + split[3], out DateTime date);
                    var listado = reservas.ListadoReservas(date);
                    TempData["5"] = date.ToString("dd/MM/yyyy");
                    return View("Index", listado);
                }
                else
                {
                    Reservas reservas = new Reservas();
                    reservas.AnularEventosReservas();
                    var listado = reservas.ListadoReservas(DateTime.Today);
                    TempData["5"] = DateTime.Today.ToString("dd/MM/yyyy");
                    return View("Index", listado);
                }
            }

        }

        // GET: Reservas/Details/5
        public ActionResult Details(int id)
        {
            //SELECT TO_CHAR(FechaInicio, 'yyyy/mm/dd hh24:mi:ss')FROM T_ENC_ENTREGAS
            Reservas reservas = new Reservas();
            var respuesta = reservas.ObtenerReservas(id);
            return View();
        }

        // GET: Reservas/Create
        [AuthorizeUser(idOperacion: 1, pantalla: 7)]
        public ActionResult Create(string Id,string fecha)
        {
            Reservas reservas = new Reservas();
            //ViewData["datos"] = datos;
            Models.Reserva datos = new Models.Reserva();
            datos.FechaEntrega = DateTime.ParseExact(fecha, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            datos.FechaEntrega2 = datos.FechaEntrega.ToString("yyyy-MM-dd");
            datos.FechaRestriccionInicio = "08:00";
            datos.FechaRestriccionFin = "16:00";
            datos.Reserva_Articulos = new List<Models.Reserva_Detalle_Articulos>();
            datos.Reserva_Casos = new List<Models.Reserva_Detalle_Casos>();
            datos.Eventos_Articulos = reservas.ObtenerEventos();
            datos.Casos_Pendientes = reservas.ObtenerCasos();
            datos.TiposDeInstalacion = reservas.TiposDeInstalaciones();
            //datos.Eventos_Articulos = new List<SelectListItem>();
            //datos.Casos_Pendientes = new List<SelectListItem>();

            //datos.Vehiculo = Id;
            return View("Modal", datos);
        }

        [AuthorizeUser(idOperacion: 1, pantalla: 11)]
        public ActionResult CreateReserva(string Id, string fecha)
        {
            Reservas reservas = new Reservas();
            //ViewData["datos"] = datos;
            Models.ReservaParcial datos = new Models.ReservaParcial();
            datos.FechaEntrega = DateTime.ParseExact(fecha, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            datos.FechaEntrega2 = datos.FechaEntrega.ToString("yyyy-MM-dd");

            //datos.Vehiculo = Id;
            return View("Reserva", datos);
        }

        [AuthorizeUser(idOperacion: 1, pantalla: 7)]
        public ActionResult CreateTraslado(string Id)
        {

            //ViewData["datos"] = datos;
            Models.Traslados datos = new Models.Traslados();
            datos.FechaEntrega = DateTime.Now;
            datos.FechaEntrega2 = DateTime.Now.ToString("yyyy-MM-dd");

            //datos.Vehiculo = Id;
            return View("Traslado", datos);
        }

        [HttpPost]
        public ActionResult CreateTraslado(string id, Models.Traslados collection)
        {
            try
            {
                // TODO: Add insert logic here
                if (string.IsNullOrEmpty(id))
                {
                    TempData["0"] = "No ha sido seleccionado un vehiculo, por favor salga de la pantalla.";

                    return View("Traslado", collection);
                }
                else
                {
                    collection.Vehiculo = id;
                }
                if (ModelState.IsValid)
                {
                    Reservas reservas = new Reservas();
                    collection.FechaEntrega = Convert.ToDateTime(collection.FechaEntrega2);

                    string respuesta = reservas.CreateTraslado(collection, "0");
                }
                else
                {
                    var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors })
                    .ToArray();
                    TempData["0"] = "Error encontrado";
                    Reservas reservas = new Reservas();

                    return View("Traslado", collection);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult CreateReserva(string id, Models.ReservaParcial collection)
        {
            try
            {
                // TODO: Add insert logic here
                if (string.IsNullOrEmpty(id))
                {
                    TempData["0"] = "No ha sido seleccionado un vehiculo, por favor salga de la pantalla.";

                    return View("Reserva", collection);
                }
                else
                {
                    collection.Vehiculo = id;
                }
                if (ModelState.IsValid)
                {
                    Reservas reservas = new Reservas();
                    collection.FechaEntrega = Convert.ToDateTime(collection.FechaEntrega2);

                    string respuesta = reservas.CrearEntregaParcial(collection, "0");
                }
                else
                {
                    var errors = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { x.Key, x.Value.Errors })
                    .ToArray();
                    TempData["0"] = "Error encontrado";
                    Reservas reservas = new Reservas();

                    return View("Reserva", collection);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Reservas/Create
        [HttpPost]
        public ActionResult Create(string id, Models.Reserva collection)
        {
            try
            {
                string respuesta = string.Empty;
                if (collection.TipoDeInstalacion ==null)
                {
                    collection.TipoDeInstalacion = "0";
                }
                // TODO: Add insert logic here
                if (string.IsNullOrEmpty(id))
                {
                    TempData["0"] = "No ha sido seleccionado un vehiculo, por favor salga de la pantalla.";
                    Reservas reservas = new Reservas();
                    if (collection.Reserva_Articulos == null)
                    {
                        collection.Reserva_Articulos = new List<Models.Reserva_Detalle_Articulos>();

                    }
                    if (collection.Reserva_Casos == null)
                    {
                        collection.Reserva_Casos = new List<Models.Reserva_Detalle_Casos>();
                    }
                    collection.FechaEntrega = Convert.ToDateTime(collection.FechaEntrega2);
                    collection.Eventos_Articulos = reservas.ObtenerEventos();
                    collection.Casos_Pendientes = reservas.ObtenerCasos();
                    collection.TiposDeInstalacion = reservas.TiposDeInstalaciones();
                    return View("Modal", collection);
                }
                else
                {
                    collection.Vehiculo = id;
                }
                if (collection.Reserva_Articulos != null || collection.Reserva_Casos != null)
                {
                    if (ModelState.IsValid)
                    {
                        var r = Request[""];
                        Reservas reservas = new Reservas();
                        collection.FechaEntrega = Convert.ToDateTime(collection.FechaEntrega2);
                        respuesta = reservas.CrearEntregaDefinitiva(collection, "0");
                      
                        TempData["0"] = respuesta;

Views/Reservas/GetListadoArticulos.cshtml
@model kalea2.Models.Reserva

<table id="invoice-edit-list-table" class="invoice-list-table style-two text-nowrap">
    <thead>
        <tr>
            <th>#</th>
            <th>Evento</th>
            <th>Articulo</th>
            <th>Descripcion</th>
            <th>Cantidad</th>
            @*<th><span>Tiempo Armado</span></th>
                <th><span>Remisionado</span></th>
                <th><span>Estado</span></th>*@
            <th>Accion</th>
        </tr>
    </thead>

    <tbody data-repeater-list="group-a" class="bg-white">

        @for (int i = 0; i < Model.Reserva_Articulos.Count; i++)
        {
            <tr data-repeater-item>
                <td class="bold">
                    @Html.DisplayFor(m => Model.Reserva_Articulos[i].Id)
                    @Html.HiddenFor(m => Model.Reserva_Articulos[i].Id)
                </td>
                <td class="NumEvento">
                    @Html.DisplayFor(m => Model.Reserva_Articulos[i].NumEvento)
                    @Html.HiddenFor(m => Model.Reserva_Articulos[i].NumEvento)
                </td>
                <td class="CodigoArticulo">
                    @Html.DisplayFor(m => Model.Reserva_Articulos[i].CodigoArticulo)
                    @Html.HiddenFor(m => Model.Reserva_Articulos[i].CodigoArticulo)
                </td>
                <td class="Descripcion">
                    @Html.DisplayFor(m => Model.Reserva_Articulos[i].Descripcion)
                    @Html.HiddenFor(m => Model.Reserva_Articulos[i].Descripcion)
                </td>
                <td class="Cantidad">
                    @Html.DisplayFor(m => Model.Reserva_Articulos[i].Cantidad)
                    @Html.HiddenFor(m => Model.Reserva_Articulos[i].Cantidad)
                    @*@Html.HiddenFor(m => Model.Reserva_Articulos[i].TiempoArmado)
                        @Html.HiddenFor(m => Model.Reserva_Articulos[i].EstadoArticulo)
                        @Html.HiddenFor(m => Model.Reserva_Articulos[i].NumEvento)*@
                </td>
                @*<td style="display:none;">
                        @Html.DisplayFor(m => Model.Reserva_Articulos[i].TiempoArmado)
                        @Html.HiddenFor(m => Model.Reserva_Articulos[i].TiempoArmado)
                    </td>
                    <td style="display:none;">
                        @Html.DisplayFor(m => Model.Reserva_Articulos[i].Remisionado)
                        @Html.HiddenFor(m => Model.Reserva_Articulos[i].Remisionado)
                    </td>
                    <td style="display:none;">
                        @Html.DisplayFor(m => Model.Reserva_Articulos[i].EstadoArticulo)
                        @Html.HiddenFor(m => Model.Reserva_Articulos[i].EstadoArticulo)
                        @Html.HiddenFor(m => Model.Reserva_Articulos[i].NumEvento)
                    </td>*@
                <td>
                    <a type="button" id="EliminarLinea" class="tr-close" data-toggle="tooltip" data-placement="top" data-original-title="Eliminar" onclick='productDelete(this);'>
                        <i class="icofont-close"></i>
                    </a>
                </td>
            </tr>
        }

    </tbody>
</table>

Views/Reservas/Reserva.cshtml
@model kalea2.Models.ReservaParcial

@*@if (TempData["0"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["0"]
    </div>
}*@


<div class="main-content d-flex flex-column flex-md-row">
    <div class="container-fluid">

        @using (Html.BeginForm())
        {
            <div class="col-12">

                <!-- Invoice Header -->
                <div class="invoice-details-header bg-white d-flex align-items-sm-center flex-column flex-sm-row mb-30 justify-content-sm-between">
                    <div class="d-flex align-items-center">
                        <a href="#" class="mr-2"><img src="~/Content/assets/img/svg/angle-left.svg" alt="" class="svg"></a>
                        <h2 class="regular mr-3 font-30">Reserva de espacio parcial</h2>
                    </div>

                    <div class="invoice-header-right d-flex align-items-center justify-content-around justify-content-sm-end mt-3 mt-sm-0">
                        <!-- Starred -->
                        <div class="star mr-20">
                            <a href="#"><img src="~/Content/assets/img/svg/star.svg" alt="" class="svg"></a>
                        </div>
                        <!-- End Starred -->
                        <!-- Delete Mail -->
                        <div class="delete_mail">
                            <a href="#"><img src="~/Content/assets/img/svg/delete.svg" alt="" class="svg"></a>
                        </div>
                        <!-- End Delete Mail -->
                        <!-- Pagination -->
                        <div class="pagination style--two d-flex flex-column align-items-center ml-2">
                            <ul class="list-inline d-inline-flex align-items-center">
                                <li>
                                    <a href="#">
                                        <img src="~/Content/assets/img/svg/left-angle.svg" alt="" class="svg">
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="current">
                                        <img src="~/Content/assets/img/svg/right-angle.svg" alt="" class="svg">
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- End Pagination -->
                    </div>
                </div>
                <!-- End Invoice Header -->
                <!-- Invoice Top -->
                <div class="invoice-pd c2-bg" data-bg-img="../../Content/assets/img/media/invoice-pattern.png">
                    <div class="row">

                        <div class="col-md-4">
                            <!-- Invoice Right -->
                            <div class="invoice-right mt-5 mt-md-0">
                                <h3 class="white font-20 mb-3">Entrega</h3>

                                <ul class="status-list">
                                    <li>
                                        <span class="key font-14">Entrega No:</span>
                                        <span class="white bold font-17"></span>
                                        <div class="col-md-12">
                                            @Html.EditorFor(modelItem => Model.Id, new { htmlAttributes = new { @class = "theme-input-style style--four", @readonly = "true" } })
                                        </div>
                                    </li>

                                    <li>
                                        @*<span class="key font-14">Fecha:</span>*@

                                        @Html.LabelFor(model => model.FechaEntrega2, htmlAttributes: new { @class = "key font-14" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.FechaEntrega2, new { htmlAttributes = new { @class = "theme-input-style style--four" } })
                                            <div class="col-md-12">
                                                @Html.ValidationMessageFor(model => model.FechaEntrega2, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        @*<input type="text" id="default-date" placeholder="28 October 2019" />*@
                                    </li>
                                    <li>
                                        @*<span class="key font-14">Fecha:</span>*@

                                        @Html.LabelFor(model => model.FechaRestriccionInicio, htmlAttributes: new { @class = "key font-14" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.FechaRestriccionInicio, new { htmlAttributes = new { @class = "theme-input-style style--four" } })
                                            <div class="col-md-12">
                                                @Html.ValidationMessageFor(model => model.FechaRestriccionInicio, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        @*<input type="text" id="default-date" placeholder="28 October 2019" />*@
                                    </li>
                                    <li>
                                        @*<span class="key font-14">Fecha:</span>*@

                                        @Html.LabelFor(model => model.FechaRestriccionFin, htmlAttributes: new { @class = "key font-14" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.FechaRestriccionFin, new { htmlAttributes = new { @class = "theme-input-style style--four" } })
                                            @Html.ValidationMessageFor(model => model.FechaRestriccionFin, "", new { @class = "text-danger" })
                                        </div>
                                        @*<input type="text" id="default-date" placeholder="28 October 2019" />*@
                                    </li>

                                </ul>
                            </div>
                            <!-- End Invoice Right -->
                        </div>
                        <div class="col-md-4">
                            <!-- Invoice Right -->
                            <div class="invoice-right mt-5 mt-md-0">
                                <h3 class="white font-20 mb-3">Horarios</h3>

                                <ul class="status-list">

                                    <li>
                                        @*<span class="key font-14">Fecha:</span>*@

                                        @Html.LabelFor(model => model.FechaInicio, htmlAttributes: new { @class = "key font-14" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.FechaInicio, new { htmlAttributes = new { @class = "theme-input-style style--four", @readonly = "true" } })
                                            @Html.ValidationMessageFor(model => model.FechaInicio, "", new { @class = "text-danger" })
                                        </div>
                                        @*<input type="text" id="default-date" placeholder="28 October 2019" />*@
                                    </li>
                                    <li>
                                        @*<span class="key font-14">Fecha:</span>*@

                                        @Html.LabelFor(model => model.FechaFin, htmlAttributes: new { @class = "key font-14" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.FechaFin, new { htmlAttributes = new { @class = "theme-input-style style--four", @readonly = "true" } })
                                            @Html.ValidationMessageFor(model => model.FechaFin, "", new { @class = "text-danger" })
                                        </div>
                                        @*<input type="text" id="default-date" placeholder="28 October 2019" />*@
                                    </li>
                                    <li>
                                        <span class="key font-14">Tiempo armado(min):</span>
                                        <span class="white bold font-17"></span>
                                        <div class="col-md-12">
                                            @Html.EditorFor(modelItem => Model.TiempoArmado, new { htmlAttributes = new { @class = "theme-input-style style--four" } })
                                            @Html.ValidationMessageFor(model => model.TiempoArmado, "", new { @class = "text-danger" })
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <!-- End Invoice Right -->
                        </div>
                        <div class="col-md-4">
                            <!-- Invoice Right -->
                            <div class="invoice-right mt-5 mt-md-0">
                                <h3 class="white font-20 mb-3">Referencias</h3>

                                <ul class="status-list">

                                    <li>
                                        <span class="key font-14">Referencia reserva:</span>
                                        <span class="white bold font-17"></span>
                                        <div class="col-md-12">
                                            @Html.EditorFor(modelItem => Model.Referencia, new { htmlAttributes = new { @class = "theme-input-style style--four" } })
                                            @Html.ValidationMessageFor(model => model.Referencia, "", new { @class = "text-danger" })
                                        </div>
                                    </li>

                                </ul>
                            </div>
                            <!-- End Invoice Right -->
                        </div>
                    </div>
                </div>
                <!-- End Invoice Top -->


                <div class="bg-white details-list-wrap">

                    <!-- Cart Collaterals -->
                    <div class="cart-collaterals style--two pt-4 pt-xl-0">
                        <div class="cart_totals calculated_shipping">


                            <div class="proceed-to-checkout invoice-edit d-flex align-items-center justify-content-end mr-20 mt-4">
                                <a href="@Url.Action("Index","Reservas")" class="btn preview">Regresar</a>
                                <button type="submit" class="btn">Guardar</button>
                            </div>
                        </div>
                    </div>
                    <!-- End Cart Collaterals -->
                </div>
                <!-- End Invoice Details List Wrapper -->

            </div>
        }

    </div>
</div>

@section Scripts {

    <script src="~/Content/assets/plugins/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/Content/assets/plugins/datepicker/datepicker.min.js"></script>
    <script src="~/Content/assets/plugins/datepicker/i18n/datepicker.en.js"></script>
    <script src="~/Content/assets/plugins/timepicker/jquery.timepicker.min.js"></script>
    <script src="~/Content/assets/plugins/datepicker/custom-form-datepicker.js"></script>
}