Controllers/TiposDeInstalacionController.cs
using kalea2.Utilidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kalea2.Controllers
{
    public class TiposDeInstalacionController : Controller
    {
        private Utilidades.TiposDeInstalacion tiposCaso;
        [AuthorizeUser(idOperacion: 0, pantalla: 3)]
        // GET: TiposCaso
        public ActionResult Index()
        {
            tiposCaso = new Utilidades.TiposDeInstalacion();
            List<Models.TiposDeCaso> tiposcaso = tiposCaso.ListadoTiposCaso();

            if (tiposcaso != null)
            {
                return View(tiposcaso);
            }
            return View();

        }

        // GET: TiposCaso/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TiposCaso/Create
        [AuthorizeUser(idOperacion: 1, pantalla: 3)]
        public ActionResult Crear()
        {
            Models.TiposDeCaso tipocaso = new Models.TiposDeCaso();
            return PartialView("Modal",tipocaso);
        }

        // POST: TiposCaso/Create
        [HttpPost]
        [AuthorizeUser(idOperacion: 1, pantalla: 3)]
        public ActionResult Crear(Models.TiposDeCaso collection)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    tiposCaso = new Utilidades.TiposDeInstalacion();
                    string respuesta = tiposCaso.CrearTipoCaso(collection);

                    if (!respuesta.Contains("Error"))
                    {
                        //List<Models.Vehiculos> ListVehiculos = tiposCaso.ListadoTiposCaso();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return View(collection);
                    }
                }


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TiposCaso/Edit/5
        [AuthorizeUser(idOperacion: 2, pantalla: 3)]
        public ActionResult Edit(int id)
        {
            tiposCaso = new Utilidades.TiposDeInstalacion();
            Models.TiposDeCaso parametroGenerals = tiposCaso.ObtenerTipoCaso(id);

            return PartialView("Modal", parametroGenerals);
        }

        // POST: TiposCaso/Edit/5
        [HttpPost]
        [AuthorizeUser(idOperacion: 2, pantalla: 3)]
        public ActionResult Edit(int id, Models.TiposDeCaso collection)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    tiposCaso = new Utilidades.TiposDeInstalacion();
                    string respuesta = tiposCaso.ActualizarTipoCaso(id, collection);

                    if (!respuesta.Contains("Error"))
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return View(collection);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TiposCaso/Delete/5
        [AuthorizeUser(idOperacion: 3, pantalla: 3)]
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add update logic here

                tiposCaso = new Utilidades.TiposDeInstalacion();
                string respuesta = tiposCaso.HabilitarInhabilitar(id);

                if (!respuesta.Contains("Error"))
                {
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: TiposCaso/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/TiposDeInstalacion/Index.cshtml
@model IEnumerable<kalea2.Models.TiposDeCaso>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="main-content d-flex flex-column flex-md-row">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Card -->
                <div class="card bg-transparent">
                    <div class="card-body bg-white mb-30">
                        <!-- Invoice Header -->
                        <div class="invoice-header d-flex align-items-sm-center media flex-column flex-sm-row">
                            <div class="invoice-header-left d-flex align-items-center position-relative">
                                <div id="PlaceHolderHere"></div>
                                <button class="btn-circle" data-toggle="ajax-modal" data-target="#addEmployee" data-url="@Url.Action("Crear", "TiposDeInstalacion")">
                                    <img src="~/Content/assets/img/svg/plus_white.svg" alt="" class="svg">
                                </button>
                            </div>

                            <div class="invoice-header-right d-flex align-items-center justify-content-end media-body mt-3 mt-sm-0">
                                <!-- Search Form -->
                                <form action="#" class="search-form">
                                    <div class="theme-input-group">
                                        <input id="fooFilter" type="text" class="theme-input-style" placeholder="Search Here">

                                        <button type="submit">
                                            <img src="~/Content/assets/img/svg/search-icon.svg" alt=""
                                                 class="svg">
                                        </button>
                                    </div>
                                </form>
                                <!-- End Search Form -->
                                <!-- Pagination -->
                                <div class="pagination style--two d-flex flex-column align-items-center ml-3">
                                    <ul class="list-inline d-inline-flex align-items-center">
                                        <li>
                                            <a href="#">
                                                <img src="~/Content/assets/img/svg/left-angle.svg" alt="" class="svg">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="current">
                                                <img src="~/Content/assets/img/svg/right-angle.svg" alt="" class="svg">
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Pagination -->
                            </div>
                        </div>
                        <!-- End Invoice Header -->
                        @Html.Partial("Tabla")
                    </div>

                   

                </div>
                <!-- End Card -->
            </div>
        </div>
    </div>
</div>

Views/TiposDeInstalacion/Modal.cshtml
@model kalea2.Models.TiposDeCaso

<!-- Contact Add New PopUp -->
<div id="addEmployee" class="modal fade">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <!-- Modal Body -->
            <div class="modal-body">
                @using (Html.BeginForm())
                 {
                    <div class="media flex-column flex-sm-row">

                        <div class="contact-account-setting media-body">

                            <h4 class="mb-4">Crear tipo de instalación</h4>

                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">

                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Codigo)

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "bold black mb-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "theme-input-style" } })
                                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" data-save="modal" class="btn mr-4">Guardar</button>
                                    <button type="button" data-dismiss="modal" class="cancel font-14 bold">Cancelar</button>
                                </div>
                            </div>


                        </div>
                    </div>
                 }

            </div>
            <!-- End Modal Body -->
        </div>
    </div>
</div>
<!-- End Contact Add New PopUp -->@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/TiposDeInstalacion/Tabla.cshtml
@model IEnumerable<kalea2.Models.TiposDeCaso>



<div class="panel" id="spy2" style="background-color:#ffffff">

    <div class="panel-body pn">
        <div class="table-responsive">
            <table class="table footable" data-filter="#fooFilter">
                <thead>
                    <tr>
                        <th>Descripción<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Estado<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </td>
                            <td>
                                @switch (item.Estado)
                                {
                                    case "A":
                                        <a class="status-btn completed" href="@Url.Action("Delete", new {id = item.Codigo})">
                                            Activo

                                        </a>
                                        @*<button type="button" class="status-btn completed">Activo</button>*@
                                        @Html.HiddenFor(modelItem => item.Estado)
                                        break;
                                    default:

                                        <a class="status-btn un_paid" href="@Url.Action("Delete", new {id = item.Codigo})">
                                            Inactivo

                                        </a>

                                        @*<button type="button" class="status-btn un_paid">Inactivo</button>*@
                                        @Html.HiddenFor(modelItem => item.Estado)
                                        break;
                                }


                            </td>
                            <td>
                                <button type="button" class="details-btn" data-toggle="ajax-modal" data-target="#addEmployee" data-url="@Url.Action($"Edit/{item.Codigo}")">
                                    Editar
                                    <img src="~/Content/assets/img/svg/plus_white.svg" alt="" class="svg">
                                </button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $(function () {

        var PlaceHolderElement = $('#PlaceHolderHere')
        $('button[data-toggle="ajax-modal"]').click(function (event) {

            var url = $(this).data('url');
            var decodeurl = decodeURIComponent(url);
            $.get(decodeurl).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('.modal').modal('show');
            })
        })


        PlaceHolderElement.on('click', '[data-save="modal"]', function (event) {
            event.preventDefault();
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');

            var sendData = form.serialize();

            console.log(actionUrl);
            console.log(sendData);

            $.post(actionUrl, sendData).done(function (data) {
                PlaceHolderElement.find('.modal').modal('hide');
                location.reload();
            }).fail(function () {

                alter("error");
            })
        })
    })
</script>

<script type="text/javascript">
    jQuery(document).ready(function () {

        //"use strict";

        //// Init Theme Core
        //Core.init();

        //// Init Demo JS
        //Demo.init();


        // Init FooTable
        $('.footable').footable();


    });
</script>