Models/Vehiculos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kalea2.Models
{
    public class Vehiculos
    {
        [Key]
        [Display(Name = "Codigo")]
        public int Codigo { get; set; }

        [Required(ErrorMessage = "Debe ingresar una descripción para el vehiculo")]
        [StringLength(254, ErrorMessage = "La descripción  no puede tener más de 254 caracteres")]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }

        [Required(ErrorMessage = "Debe ingresar un numero de placa")]
        [StringLength(7, ErrorMessage = "El valor no puede tener más de 7 caracteres")]
        [Display(Name = "Placa")]
        public string Placa { get; set; }

        [Required(ErrorMessage = "Debe ingresar un nombre de piloto")]
        [StringLength(100, ErrorMessage = "El piloto no puede tener más de 100 caracteres")]
        [Display(Name = "Piloto")]
        public string Piloto { get; set; }

        [Required(ErrorMessage = "Debe ingresar un volumen de carga")]
        [StringLength(50, ErrorMessage = "El volumen de carga no puede tener más de 50 caracteres")]
        [Display(Name = "Volumen de carga (m^3)")]
        [DataType(DataType.Currency)]
        public string VolumenCarga { get; set; }

        [Required(ErrorMessage = "Debe ingresar un peso de carga")]
        [StringLength(50, ErrorMessage = "El peso de carga no puede tener más de 50 caracteres")]
        [Display(Name = "Peso de carga (KG)")]
        [DataType(DataType.Currency)]
        public string PesoCarga { get; set; }

        [Required(ErrorMessage = "Debe ingresar un peso de carga")]
        [Display(Name = "Hora inicio de labores")]
        [DataType(DataType.Time)]
        public string HoraInicioLabores { get; set; }

        public bool Seleccionado { get; set; }


 
        public List<SelectListItem> TrasladosSiNo { get; set; }

        [Required(ErrorMessage = "Debe seleccionar si el vehiculo es para traslado o no.")]
        [Display(Name = "Traslados")]
        public string TrasladoSiNo { get; set; }
        public string Estado { get; set; }
        public string UsrCreacion { get; set; }

        public Vehiculos()
        {
            TrasladosSiNo = new List<SelectListItem>();
            TrasladosSiNo.Add(new SelectListItem { Text = "No", Value = "No",Selected= true });
            TrasladosSiNo.Add(new SelectListItem { Text ="Si", Value = "Si" });
           

        }
    }
}

Controllers/VehiculosController.cs
using kalea2.Utilidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kalea2.Controllers
{
    public class VehiculosController : Controller
    {
        private Utilidades.Vehiculos vehiculos;
        // GET: Vehiculos
        [AuthorizeUser(idOperacion: 0, pantalla: 5)]
        public ActionResult Index()
        {
            if (TempData["0"] != null)
            {
                var t = TempData["0"].ToString();
                if (!string.IsNullOrEmpty(t))
                {
                    if (t.Contains("Error"))
                    {
                        ViewBag.Mensaje = t;
                    }
                    else if (t.Contains("Vehiculo"))
                    {
                        ViewBag.Exitoso = t;
                    }
                }
            }
            vehiculos = new Utilidades.Vehiculos();
            List<Models.Vehiculos> ListVehiculos = vehiculos.ListadoVehiculos();

            if (ListVehiculos != null)
            {
                return View(ListVehiculos);
            }
            return View();
        }

        // GET: Vehiculos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Vehiculos/Create
        [AuthorizeUser(idOperacion: 1, pantalla: 5)]
        public ActionResult Create()
        {
            Models.Vehiculos vehiculo = new Models.Vehiculos();
            return View(vehiculo);
        }

        // POST: Vehiculos/Create
        [HttpPost]
        [AuthorizeUser(idOperacion: 1, pantalla: 5)]
        public ActionResult Create(Models.Vehiculos vehiculo)
        {
            try
            {
                // TODO: Add insert logic here

                if (ModelState.IsValid)
                {
                    vehiculos = new Utilidades.Vehiculos();
                    string respuesta = vehiculos.CrearVehiculo(vehiculo);
                    TempData["0"] = respuesta;
                    if (!respuesta.Contains("Error"))
                    {
                        List<Models.Vehiculos> ListVehiculos = vehiculos.ListadoVehiculos();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        
                        ViewBag.Mensaje = respuesta;
                    
                        return View(vehiculo);
                    }
                }
                else
                {
                    var errors = ModelState
                         .Where(x => x.Value.Errors.Count > 0)
                         .Select(x => new { x.Value.Errors })
                         .ToArray();
                    string Error = string.Empty;
                    foreach (var item in errors)
                    {
                        TempData["0"] += item.Errors[0].ErrorMessage + "; ";
                    }
                    return View(vehiculo);
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Vehiculos/Edit/5
        [AuthorizeUser(idOperacion: 2, pantalla: 5)]
        public ActionResult Edit(int id)
        {
         
            vehiculos = new Utilidades.Vehiculos();
            Models.Vehiculos vehiculo = vehiculos.ObtenerVehiculo(id);
            return View(vehiculo);
        }

        // POST: Vehiculos/Edit/5
        [HttpPost]
        [AuthorizeUser(idOperacion: 2, pantalla: 5)]
        public ActionResult Edit(int id, Models.Vehiculos collection)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    vehiculos = new Utilidades.Vehiculos();
                    string respuesta = vehiculos.ActualizarVehiculo(id,collection);
                    TempData["0"] = respuesta;
                    if (!respuesta.Contains("Error"))
                    {
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    var errors = ModelState
                         .Where(x => x.Value.Errors.Count > 0)
                         .Select(x => new { x.Value.Errors })
                         .ToArray();
                    string Error = string.Empty;
                    foreach (var item in errors)
                    {
                        TempData["0"] += item.Errors[0].ErrorMessage + "; ";
                    }
                    return View(collection);
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vehiculos/Delete/5
        [AuthorizeUser(idOperacion: 3, pantalla: 5)]
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add update logic here
              
                vehiculos = new Utilidades.Vehiculos();
                string respuesta = vehiculos.HabilitarInhabilitar(id);
                TempData["0"] = respuesta;
                if (!respuesta.Contains("Error"))
                {
                    return RedirectToAction("Index");
                }
               
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Vehiculos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Vehiculos/Create.cshtml
@model kalea2.Models.Vehiculos

@if (ViewBag.Mensaje != null)
{

    <body onload="My_onLoad('@ViewBag.Mensaje')">
    </body>
}
else if (ViewBag.Exitoso != null)
{
    <body onload="My_onLoad2('@ViewBag.Exitoso')">
    </body>
}

<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <!-- Base Horizontal Form With Icons -->
                <div class="form-element py-30 multiple-column">
                    <h4 class="font-20 mb-20">Crear vehiculo</h4>
                    <!-- Form -->
                    <form action="Create" method="POST">

                        <div class="row">
                            <div class="col-lg-6">
                                <!-- Form Group -->
                                <div class="form-group">

                                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Ingrese una descripción para el vehículo" } })
                                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <!-- End Form Group -->
                                <!-- Form Group -->
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Ingrese número de placa de vehículo" } })
                                        @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <!-- End Form Group -->
                                <!-- Form Group -->
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Piloto, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.Piloto, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Ingrese nombre de piloto" } })
                                        @Html.ValidationMessageFor(model => model.Piloto, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.TrasladoSiNo, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                    <div class="col-md-12">
                                        @Html.DropDownListFor(modelItem => modelItem.TrasladoSiNo, Model.TrasladosSiNo,
                                                              " -- Vehiculo para traslado? --", new { @class = "theme-input-style" })
                                        @Html.ValidationMessageFor(model => model.TrasladoSiNo, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                                <!-- End Form Group -->
                            </div>

                            <div class="col-lg-6">
                                <!-- Form Group -->
                                <div class="form-group">
                                    @Html.LabelFor(model => model.PesoCarga, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.PesoCarga, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Peso de carga", @type = "number" } })
                                        @Html.ValidationMessageFor(model => model.PesoCarga, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <!-- End Form Group -->
                                <!-- Form Group -->
                                <div class="form-group">
                                    @Html.LabelFor(model => model.VolumenCarga, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.VolumenCarga, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Volumen de carga", @type = "number" } })
                                        @Html.ValidationMessageFor(model => model.VolumenCarga, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.HoraInicioLabores, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                    <div class="col-md-12">
                                        @Html.EditorFor(model => model.HoraInicioLabores, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Volumen de carga" } })
                                        @Html.ValidationMessageFor(model => model.HoraInicioLabores, "", new { @class = "text-danger" })

                                    </div>
                                </div>

                                <!-- End Form Group -->
                            </div>
                        </div>


                        <!-- Form Row -->
                        <div class="form-row">
                            <div class="col-12 text-right">
                                <button type="submit" class="btn long">Guardar</button>
                            </div>
                        </div>
                        <!-- End Form Row -->
                    </form>
                    <!-- End Form -->
                </div>
                <!-- End Horizontal Form With Icons -->
            </div>
        </div>
    </div>
</div>
<!-- End Main Content -->
@section Scripts {
    <script type="text/javascript">
        function My_onLoad(mensaje) {
            Swal.fire({ title: "Error!", text: mensaje, type: "error", confirmButtonClass: "btn long", buttonsStyling: !1 });
        }
    </script>

    <script type="text/javascript">
        function My_onLoad2(mensaje) {
            Swal.fire({ title: "Excelente!", text: mensaje, type: "success", confirmButtonClass: "btn long", buttonsStyling: !1 });
        }
    </script>

}

Views/Vehiculos/Edit.cshtml
@model kalea2.Models.Vehiculos

@if (ViewBag.Mensaje != null)
{

    <body onload="My_onLoad('@ViewBag.Mensaje')">
    </body>
}
else if (ViewBag.Exitoso != null)
{
    <body onload="My_onLoad2('@ViewBag.Exitoso')">
    </body>
}

<div class="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <!-- Base Horizontal Form With Icons -->
                <div class="form-element py-30 multiple-column">
                    <h4 class="font-20 mb-20">Editar vehiculo</h4>
                    <!-- Form -->
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Codigo)

                            <div class="row">
                                <div class="col-lg-6">
                                    <!-- Form Group -->
                                    <div class="form-group">

                                        @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Ingrese una descripción para el vehículo" } })
                                            @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <!-- End Form Group -->
                                    <!-- Form Group -->
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Ingrese número de placa de vehículo" } })
                                            @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <!-- End Form Group -->
                                    <!-- Form Group -->
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Piloto, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.Piloto, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Ingrese nombre de piloto" } })
                                            @Html.ValidationMessageFor(model => model.Piloto, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TrasladoSiNo, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                        <div class="col-md-12">
                                            @Html.DropDownListFor(modelItem => modelItem.TrasladoSiNo, Model.TrasladosSiNo,
                                                                  " -- Vehiculo para traslado --", new { @class = "theme-input-style" })
                                            @Html.ValidationMessageFor(model => model.TrasladoSiNo, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                    <!-- End Form Group -->
                                </div>

                                <div class="col-lg-6">
                                    <!-- Form Group -->
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.PesoCarga, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.PesoCarga, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Peso de carga", @type = "number" } })
                                            @Html.ValidationMessageFor(model => model.PesoCarga, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <!-- End Form Group -->
                                    <!-- Form Group -->
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.VolumenCarga, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.VolumenCarga, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Volumen de carga", @type = "number" } })
                                            @Html.ValidationMessageFor(model => model.VolumenCarga, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.HoraInicioLabores, htmlAttributes: new { @class = "font-14 bold mb-2" })
                                        <div class="col-md-12">
                                            @Html.EditorFor(model => model.HoraInicioLabores, new { htmlAttributes = new { @class = "theme-input-style", @placeholder = "Volumen de carga" } })
                                            @Html.ValidationMessageFor(model => model.HoraInicioLabores, "", new { @class = "text-danger" })

                                        </div>
                                    </div>

                                    <!-- End Form Group -->
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col-12 text-right">
                                    <button type="submit" class="btn long">Guardar</button>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <!-- End Horizontal Form With Icons -->
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        function My_onLoad(mensaje) {
            Swal.fire({ title: "Error!", text: mensaje, type: "error", confirmButtonClass: "btn long", buttonsStyling: !1 });
        }
    </script>

    <script type="text/javascript">
        function My_onLoad2(mensaje) {
            Swal.fire({ title: "Excelente!", text: mensaje, type: "success", confirmButtonClass: "btn long", buttonsStyling: !1 });
        }
    </script>

}

Views/Vehiculos/Index.cshtml
@model IEnumerable<kalea2.Models.Vehiculos>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Mensaje != null)
{

    <body onload="My_onLoad('@ViewBag.Mensaje')">
    </body>
}
else if (ViewBag.Exitoso != null)
{
    <body onload="My_onLoad2('@ViewBag.Exitoso')">
    </body>
}

<div class="main-content d-flex flex-column flex-md-row">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Card -->
                <div class="card bg-transparent">
                    <div class="card-body bg-white mb-30">
                        <!-- Invoice Header -->
                        <div class="invoice-header d-flex align-items-sm-center media flex-column flex-sm-row">
                            <div class="invoice-header-left d-flex align-items-center position-relative">
                                <div id="PlaceHolderHere"></div>
                                <div class="">
                                    <a class="btn-circle" href="@Url.Action("Create","Vehiculos")">
                                        <img src="~/Content/assets/img/svg/plus_white.svg" alt="" class="svg">
                                    </a>
                                </div>
                                @*<div class="delete_mail">
                    <a href="@Url.Action("Delete")"><img src="~/Content/assets/img/svg/delete.svg" alt="" class="svg"></a>
                </div>*@
                                <!-- End Delete Mail -->
                                <!-- Dropdown Button -->
                                <!-- End Dropdown Button -->
                            </div>

                            <div class="invoice-header-right d-flex align-items-center justify-content-end media-body mt-3 mt-sm-0">
                                <!-- Search Form -->
                                <form action="#" class="search-form">
                                    <div class="theme-input-group">
                                        <input id="fooFilter" type="text" class="theme-input-style" placeholder="Search Here">

                                        <button type="submit">
                                            <img src="~/Content/assets/img/svg/search-icon.svg" alt=""
                                                 class="svg">
                                        </button>
                                    </div>
                                </form>
                                <!-- End Search Form -->
                                <!-- Pagination -->
                                <div class="pagination style--two d-flex flex-column align-items-center ml-3">
                                    <ul class="list-inline d-inline-flex align-items-center">
                                        <li>
                                            <a href="#">
                                                <img src="~/Content/assets/img/svg/left-angle.svg" alt="" class="svg">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="current">
                                                <img src="~/Content/assets/img/svg/right-angle.svg" alt="" class="svg">
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Pagination -->
                            </div>
                        </div>
                        <!-- End Invoice Header -->
                        @Html.Partial("Tabla")
                    </div>

                   

                </div>
                <!-- End Card -->
            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script>
        $(function () {
            var PlaceHolderElement = $('#PlaceHolderHere')
            $('button[data-toggle="ajax-modal"]').click(function (event) {
                console.log("Entro");
                var url = $(this).data('url');
                var decodeurl = decodeURIComponent(url);
                $.get(decodeurl).done(function (data) {
                    PlaceHolderElement.html(data);
                    PlaceHolderElement.find('.modal').modal('show');
                })
            })


            PlaceHolderElement.on('click', '[data-save="modal"]', function (event) {
                event.preventDefault();
                var form = $(this).parents('.modal').find('form');
                var actionUrl = form.attr('action');

                var sendData = form.serialize();

                console.log(actionUrl);
                console.log(sendData);

                $.post(actionUrl, sendData).done(function (data) {
                    PlaceHolderElement.find('.modal').modal('hide');
                    location.reload();
                }).fail(function () {

                    alter("error");
                })
            })
        })
    </script>

    <script type="text/javascript">
        function My_onLoad(mensaje) {
            Swal.fire({ title: "Error!", text: mensaje, type: "error", confirmButtonClass: "btn long", buttonsStyling: !1 });
        }
    </script>

    <script type="text/javascript">
        function My_onLoad2(mensaje) {
            Swal.fire({ title: "Excelente!", text: mensaje, type: "success", confirmButtonClass: "btn long", buttonsStyling: !1 });
        }
    </script>
}