Models/CasosEntregas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace kalea2.Models
{
    public class CasosEntregas
    {
        public int Id { get; set; }
        public string NombreCliente { get; set; }
        public string ApellidoCliente { get; set; }
        public string DireccionCliente { get; set; }
        public string NumTelCliente { get; set; }
        public string NitCliente { get; set; }
        public string FechaEntrega { get; set; }
        public string VehiculoId { get; set; }

        public List<CasosEntregasDetalle> DetalleCE { get; set; }

    }


    public class CasosEntregasDetalle
    { 
        public string Evento { get; set; }
        public string Articulo { get; set; }
        public int CantidadArticulo { get; set; }
        /// <summary>
        ///  Nos indica si el articulo fue dada de baja de inventario o no
        /// </summary>
        public string Remisionado { get; set; }
        /// <summary>
        /// El estado nos indica si fue remisionado por Caja rapida, Domicilio o tienda
        /// </summary>
        public string EstadoArticulo { get; set; }
        public decimal Total { get; set; }
    }
}

Controllers/CasosEntregasController.cs
using kalea2.Utilidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kalea2.Controllers
{
    public class CasosEntregasController : Controller
    {
        Utilidades.CasosEntregas CasosEntregas;
        // GET: CasosEntregas
        [AuthorizeUser(idOperacion: 0, pantalla: 6)]
        public ActionResult Index()
        {

            if (TempData["0"] != null)
            {
                var t = TempData["0"].ToString();
                if (!string.IsNullOrEmpty(t))
                {
                    if (t.Contains("Error"))
                    {
                        ViewBag.Mensaje = t;
                    }
                    else if (t.Contains("Entrega"))
                    {
                        ViewBag.Exitoso = t;
                    }
                }
            }

            Utilidades.Reservas re = new Utilidades.Reservas();
            re.AnularEventosReservas();

            CasosEntregas = new Utilidades.CasosEntregas();

            string[] split = this.Request.RawUrl.Split('=');
            if (split.Length>1)
            {
                if (!string.IsNullOrEmpty(split[1]))
                {
                    Models.Reserva reserva = CasosEntregas.GetEntrega(split[1].ToString());
                   
                    if (!string.IsNullOrEmpty(reserva.Id.ToString()))
                    {
                        List<Models.Reserva> listado = new List<Models.Reserva>();
                        listado.Add(reserva);
                        return View(listado);
                    }
                    else
                    {
                        List<Models.Reserva> listado = new List<Models.Reserva>();
                        return View( listado);
                    }
                }
            }
            return View(CasosEntregas.Entregas());
            //return View("View");
        }

        public ActionResult Create()
        {
            Models.CasosEntregas casoEntrega = new Models.CasosEntregas();
            return View(casoEntrega);
        }

        [AuthorizeUser(idOperacion: 2, pantalla: 6)]
        public ActionResult Edit(int id)
        {

            CasosEntregas = new Utilidades.CasosEntregas();

            Models.Reserva reserva = CasosEntregas.GetEntrega(id.ToString());

            if (!string.IsNullOrEmpty(reserva.Id.ToString()))
            {
                return View("Modal", reserva);
            }
            return RedirectToAction("Index");
           
        }

        [HttpPost]
        public ActionResult Edit(int id, Models.Reserva reserva)
        {
            try
            {
                CasosEntregas = new Utilidades.CasosEntregas();
                if (reserva.TipoDeInstalacion == null)
                {
                    reserva.TipoDeInstalacion = "0";
                }
                if (ModelState.IsValid)
                {
                    if (reserva.Reserva_Articulos == null && reserva.Reserva_Casos == null)
                    {
                        if (reserva.Reserva_Articulos.Count == 0)
                        {
                            ViewBag.Alerta = "Debe seleccionar al menos 1 evento o 1 caso para la entrega";
                            Models.Reserva reservatemp = CasosEntregas.GetEntrega(id.ToString());
                            reserva.FechaEntrega = Convert.ToDateTime(reserva.FechaEntrega2);
                            reserva.Casos_Pendientes = reservatemp.Casos_Pendientes;
                            reserva.Eventos_Articulos = reservatemp.Eventos_Articulos;
                            reserva.Reserva_Articulos = reservatemp.Reserva_Articulos;
                            reserva.Reserva_Casos = reservatemp.Reserva_Casos;
                            reserva.TiposDeInstalacion = reservatemp.TiposDeInstalacion;
                            return View("Modal", reserva);
                        }
                    }
                    //else
                    //{
                    //    ViewBag.Alerta = "Debe seleccionar al menos 1 evento o 1 caso para la entrega";
                    //    Models.Reserva reservatemp = CasosEntregas.GetEntrega(id.ToString());
                    //    reserva.FechaEntrega = Convert.ToDateTime(reserva.FechaEntrega2);
                    //    reserva.Casos_Pendientes = reservatemp.Casos_Pendientes;
                    //    reserva.Eventos_Articulos = reservatemp.Eventos_Articulos;
                    //    reserva.Reserva_Articulos = reservatemp.Reserva_Articulos;
                    //    reserva.Reserva_Casos = reservatemp.Reserva_Casos;
                    //    return View("Modal", reserva);
                    //}
                    
                    Utilidades.Reservas reservas = new Utilidades.Reservas();
                    reserva.FechaEntrega = Convert.ToDateTime(reserva.FechaEntrega2);
                    TempData["0"] =  reservas.EditarEntregaDefinitiva(reserva, "0", id.ToString());
                }
                else
                {
                    var errors = ModelState
                       .Where(x => x.Value.Errors.Count > 0)
                       .Select(x => new { x.Key, x.Value.Errors })
                       .ToArray();
                    Utilidades.Reservas reservas = new Utilidades.Reservas();
                    if (!string.IsNullOrEmpty(reserva.Id.ToString()))
                    {
                        Models.Reserva reservatemp = CasosEntregas.GetEntrega(id.ToString());
                        reserva.FechaEntrega = Convert.ToDateTime(reserva.FechaEntrega2);
                        reserva.Casos_Pendientes = reservatemp.Casos_Pendientes;
                        reserva.Eventos_Articulos = reservatemp.Eventos_Articulos;
                        reserva.Reserva_Articulos = reservatemp.Reserva_Articulos;
                        reserva.Reserva_Casos = reservatemp.Reserva_Casos;
                        reserva.TiposDeInstalacion = reservatemp.TiposDeInstalacion;
                        string Error = string.Empty;
                        foreach (var item in errors)
                        {
                            ViewBag.Mensaje += item.Errors[0].ErrorMessage + "; ";
                        }

                        return View("Modal", reserva);
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {

                ViewBag.Alerta = "Ocurrio un error inesperado en la aplicacion.";
                Models.Reserva reservatemp = CasosEntregas.GetEntrega(id.ToString());
                reserva.FechaEntrega = Convert.ToDateTime(reserva.FechaEntrega2);
                reserva.Casos_Pendientes = reservatemp.Casos_Pendientes;
                reserva.Eventos_Articulos = reservatemp.Eventos_Articulos;
                reserva.Reserva_Articulos = reservatemp.Reserva_Articulos;
                reserva.Reserva_Casos = reservatemp.Reserva_Casos;
                return View("Modal", reserva);
            }
           
        }


        [HttpPost]
        public ActionResult Filtro(int id)
        {
            CasosEntregas = new Utilidades.CasosEntregas();

            Models.Reserva reserva = CasosEntregas.GetEntrega(id.ToString());

            if (!string.IsNullOrEmpty(reserva.Id.ToString()))
            {
                List<Models.Reserva> listado = new List<Models.Reserva>();
                listado.Add(reserva);
                return PartialView("Tabla", reserva);
            }
            return RedirectToAction("Index");

        }

        [HttpPost]
        [AuthorizeUser(idOperacion: 3, pantalla: 6)]
        public ActionResult Delete(int id)
        {
            try
            {
                CasosEntregas = new Utilidades.CasosEntregas();

                string respuesta = CasosEntregas.AnularEntrega(id.ToString());
                CasosEntregas.RordenarTrasAnulacion(id.ToString());
                return Json(respuesta);
            }
            catch
            {
                return Json("false");
            }
        }
    }
}

Views/CasosEntregas/Index.cshtml
@model IEnumerable<kalea2.Models.Reserva>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Mensaje != null)
{

    <body onload="My_onLoad('@ViewBag.Mensaje')">
    </body>
}
else if (ViewBag.Exitoso != null)
{
    <body onload="My_onLoad2('@ViewBag.Exitoso')">
    </body>
}



<div class="main-content d-flex flex-column flex-md-row">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Card -->
                <div class="card bg-transparent">
                    <div class="card-body bg-white mb-30">
                        <!-- Invoice Header -->
                        <div class="invoice-header d-flex align-items-sm-center media flex-column flex-sm-row">
                            <div class="invoice-header-left d-flex align-items-center position-relative">
                                <div id="PlaceHolderHere"></div>

                            </div>

                            <div class="invoice-header-right d-flex align-items-center justify-content-end media-body mt-3 mt-sm-0">
                                <!-- Search Form -->
                                <form action="#" class="search-form">
                                    <div class="theme-input-group">
                                        <input id="fooFilter" name="fooFilter" type="text" class="theme-input-style" placeholder="Ingrese un criterio de filtro">

                                        <button type="">

                                            <img src="~/Content/assets/img/svg/search-icon.svg" alt=""
                                                 class="svg">
                                        </button>
                                    </div>
                                </form>
                                <!-- End Search Form -->
                                <!-- Pagination -->

                                @*<div class="pagination style--two d-flex flex-column align-items-center ml-3">
                                    <ul class="list-inline d-inline-flex align-items-center">
                                        <li>
                                            <a href="#">
                                                <img src="~/Content/assets/img/svg/left-angle.svg" alt="" class="svg">
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" class="current">
                                                <img src="~/Content/assets/img/svg/right-angle.svg" alt="" class="svg">
                                            </a>
                                        </li>
                                    </ul>
                                </div>*@
                                <!-- End Pagination -->
                            </div>
                            <!-- End Invoice Header -->

                        </div>
                        @Html.Partial("Tabla")
                    </div>

                   

                </div>
                <!-- End Card -->
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        var PlaceHolderElement = $('#PlaceHolderHere')
        $('button[data-toggle="ajax-modal"]').click(function (event) {
            console.log("Entro");
            var url = $(this).data('url');
            var decodeurl = decodeURIComponent(url);
            $.get(decodeurl).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('.modal').modal('show');
            })
        })


        PlaceHolderElement.on('click', '[data-save="modal"]', function (event) {
            event.preventDefault();
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');

            var sendData = form.serialize();

            console.log(actionUrl);
            console.log(sendData);

            $.post(actionUrl, sendData).done(function (data) {
                PlaceHolderElement.find('.modal').modal('hide');
                location.reload();
            }).fail(function () {

                alter("error");
            })
        })
    })
</script>

<script type="text/javascript">
    function My_onLoad(mensaje) {
        Swal.fire({ title: "Error!", text: mensaje, type: "error", confirmButtonClass: "btn long", buttonsStyling: !1 });
    }
</script>

<script type="text/javascript">
    function My_onLoad2(mensaje) {
        Swal.fire({ title: "Excelente!", text: mensaje, type: "success", confirmButtonClass: "btn long", buttonsStyling: !1 });
    }
</script>

Views/CasosEntregas/Tabla.cshtml
@model IEnumerable<kalea2.Models.Reserva>



<div class="panel" id="spy2" style="background-color:#ffffff">
    <div class="panel-body pn">
        <div class="table-responsive">
            <table class="table footable" data-filter="#fooFilter" data-paging="true">
                <thead>
                    <tr>
                        <th># Entrega<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Fecha<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Nombre<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Telefono<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Celular<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Vehiculo<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Estado<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Tipo<img src="~/Content/assets/img/svg/table-down-arrow.svg" alt="" class="svg"></th>
                        <th>Accion</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                                @Html.HiddenFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaEntrega2)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombreCliente)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Telefono)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Celular)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Vehiculo)
                            </td>
                            <td>
                                @switch (item.Estado)
                                {
                                    case "A":
                                        <a class="status-btn completed">
                                            Activo
                                        </a>
                                        @Html.HiddenFor(modelItem => item.Estado)
                                        break;
                                    case "AN":
                                        <a class="status-btn un_paid">
                                            Anulado
                                        </a>
                                        @Html.HiddenFor(modelItem => item.Estado)
                                        break;
                                }
                            </td>
                            <td>
                                @switch (item.ColorTipoEvento)
                                {
                                    case "#00b050":
                                        <a>
                                            Definitivo
                                        </a>
                                        break;
                                    case "#FF0000":
                                        <a>
                                            Definitivo
                                        </a>
                                        break;
                                    case "#ffff00":
                                        <a>
                                            Temporal
                                        </a>
                                        break;
                                    case "#FF5733":
                                        <a>
                                            Traslado
                                        </a>
                                        break;
                                }
                            </td>

                            <td>

                                @switch (item.Estado)
                                {
                                    case "A":
                                        <a class="details-btn" href="@Url.Action("Edit", new {id = item.Id})">
                                            Editar
                                            <img src="~/Content/assets/img/svg/plus_white.svg" alt="" class="svg">
                                        </a>
                                        <button class="details-btn" onclick="Eliminar('@item.Id')">
                                            Anular
                                            <img src="~/Content/assets/img/svg/plus_white.svg" alt="" class="svg">
                                        </button>
                                        @Html.HiddenFor(modelItem => item.Estado)
                                        break;

                                }
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot class="hide-if-no-paging">
                    <tr>
                        <td colspan="5" class="text-center">
                            <ul class="pagination"></ul>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<script>
    $(function () {

        var PlaceHolderElement = $('#PlaceHolderHere')
        $('button[data-toggle="ajax-modal"]').click(function (event) {

            var url = $(this).data('url');
            var decodeurl = decodeURIComponent(url);
            $.get(decodeurl).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('.modal').modal('show');
            })
        })


        PlaceHolderElement.on('click', '[data-save="modal"]', function (event) {
            event.preventDefault();
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');

            var sendData = form.serialize();

            console.log(actionUrl);
            console.log(sendData);

            $.post(actionUrl, sendData).done(function (data) {
                PlaceHolderElement.find('.modal').modal('hide');
                location.reload();
            }).fail(function () {

                alter("error");
            })
        })
    })
</script>

<script>

        function Eliminar(id) {
        Swal.fire({
            title: "Esta seguro de anular la entrega seleccionada?",
            text: "Si anula esta entrega, no podra recuperarla!",
            type: "warning",
            showCancelButton: !0,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Si, anular la entrega!",
            confirmButtonClass: "btn long",
            cancelButtonClass: "btn long bg-danger ml-1",
            buttonsStyling: !1,
        }).then(function (t) {


            t.value

            if (t.value) {

                $.ajax({
                type: 'POST',
                url: '@Url.Action("Delete", "CasosEntregas")',

                dataType: 'json',
                data: {
                    id: id
                },
                success: function (states) {
                    /* alert("Orden");*/

                    console.log(states);

                    if (states.includes("Error")) {
                        Swal.fire({ title: "Error!", text: "Ocurrio un error al anular la entrega. " + ex, type: "error", confirmButtonClass: "btn long", buttonsStyling: !1 });
                    } else {
                        Swal.fire({ title: "Excelente!", text: "Entrega anulada exitosamente!", type: "success", confirmButtonClass: "btn long", buttonsStyling: !1 });
                        /*location.reload();*/
                    }
                },
                    error: function (ex) {
                        console.log(states);
                    Swal.fire({ title: "Error!", text: "Ocurrio un error al ordenes las entregas. Error:" + ex, type: "error", confirmButtonClass: "btn long", buttonsStyling: !1 });
                }
            })

            } else {
                t.dismiss === Swal.DismissReason.cancel && Swal.fire({ title: "Cancelado", text: "La entrega no se a anulado! :)", type: "error", confirmButtonClass: "btn btn-success" });
            }

        });
    };
</script>

<script type="text/javascript">
    jQuery(document).ready(function () {

        //"use strict";

        //// Init Theme Core
        //Core.init();

        //// Init Demo JS
        //Demo.init();


        // Init FooTable
        $('.footable').footable();


    });

</script>